'use client'


export { StarterKit } from '@tiptap/starter-kit'
export { Highlight } from '@tiptap/extension-highlight'
// export { CharacterCount } from '@tiptap/extension-character-count'
export { Underline } from '@tiptap/extension-underline'
// export { Placeholder } from '@tiptap/extension-placeholder'
// export { Emoji, gitHubEmojis } from '@tiptap-pro/extension-emoji'
// export { TextAlign } from '@tiptap/extension-text-align'
export { TextStyle } from '@tiptap/extension-text-style'
export { FontFamily } from '@tiptap/extension-font-family'
// export { Typography } from '@tiptap/extension-typography'
// export { Color } from '@tiptap/extension-color'
// export { FocusClasses as Focus } from '@tiptap/extension-focus'
// export { Dropcursor } from '@tiptap/extension-dropcursor'
export { Subscript } from '@tiptap/extension-subscript'
export { TableOfContent } from '@tiptap-pro/extension-table-of-content'
export { Superscript } from '@tiptap/extension-superscript'
export { Paragraph } from '@tiptap/extension-paragraph'
export { CodeBlock } from '@tiptap/extension-code-block'
export { BulletList } from '@tiptap/extension-bullet-list'
export { OrderedList } from '@tiptap/extension-ordered-list'
export { TaskItem } from '@tiptap/extension-task-item'
export { TaskList } from '@tiptap/extension-task-list'
export { FileHandler } from '@tiptap-pro/extension-file-handler'

export { Link } from './Link'
export { SlashCommand } from './SlashCommand'
export { FontSize } from './FontSize'


